[tool.ruff]
line-length = 160
src = ["main", "config"]
target-version = "py311"
extend-exclude = [
    "migrations",
    "static",
    "templates",
    ".venv",
    "venv",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "N"]
ignore = []
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
